# Other Matrix Operations

There are a variety of other matrix operations that are used within machine learning. Most of these are simpler than matrix multiplication, but regardless, they are important to know and use.

In [211]:
import numpy as np
import matplotlib.pyplot

## Transpose

In [212]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

**Problem:** Write a function that does the transpose. If you need to, try working it out by hand first and then coding.

In [213]:
def transpose(A):
    #I'd guess that it transfers the first column to the first row, second to second, and so on
    R = np.empty([A.shape[1], A.shape[0]])
    #For loop:
    #Go through numbers in one
    #For each number in one, add the number[s] below to the array as well
    for k in range(A.shape[1]):
        #Loops through each number on the top
        for j in range(A.shape[0]):
            #Then, go through each number below
            #Add set (length, height) to array
            R[k,j] = A[j,k]
    return R

In [214]:
for i in range(10):
    shape = np.random.randint(low=1, high=100, size=2)
    A = np.random.randn(*shape)
    B = np.random.randn(*shape)
    assert np.allclose(A.T, transpose(A))
print('Success')

Success


**Problem:** Verify the first 3 properties of the matrix transpose listed in [Wikipedia](https://en.wikipedia.org/wiki/Transpose#Properties). Namely,

$$\begin{align}
\left(\mathbf {A} ^{\mathrm {T} }\right)^{\mathrm {T} }&=\mathbf {A} \quad  \\
\left(\mathbf {A} +\mathbf {B} \right)^{\mathrm {T} }&=\mathbf {A} ^{\mathrm {T} }+\mathbf {B} ^{\mathrm {T}} \\
\left(\mathbf {AB} \right)^{\mathrm {T} } &=\mathbf {B} ^{\mathrm {T} }\mathbf {A} ^{\mathrm {T} }
\end{align}$$

Use the built-in Numpy functions `A.dot(B)`, `A.T`, and `A + B` to demonstrate this numerically. Make sure you verify this for non-square matrices. Meaning ` A.shape[0] != A.shape[1] `.

In [215]:
A = np.random.randn(*shape)
B = np.random.randn(*shape)
C = np.random.randn(shape[1], np.random.randint(1,10))
assert np.allclose(A.T.T, A)
print("Involution works")
assert np.allclose(A.T + B.T, (A+B).T)
print("Respects Law of Addition")
assert np.allclose(A.dot(C).T, (C.T).dot(A.T))
print("Whatever the third law is")

Involution works
Respects Law of Addition
Whatever the third law is


## Matrix-Vector Multiplication

A matrix times a vector is the same as a matrix times a matrix if the second matrix is a column,

In [216]:
A = np.arange(30).reshape((5, 6))
b = np.arange(6).reshape((6, 1))
print(A)
print(b)
print(A.dot(b))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
[[ 55]
 [145]
 [235]
 [325]
 [415]]


**Problem:** If I have a matrix $ A $ with shape `(N, M)` and multiply it by a vector $ x $. What shape must $ x $ be? What shape will $ A x $ be? Verify this numerically.

In [217]:
import random
shared = random.randint(1, 10)
other = random.randint(1, 10)
A = np.arange(shared * other).reshape((other, shared))
b = np.arange(shared * 1).reshape((shared, 1))
print("N, M Array:")
print(A)
print("Vector:")
print(b)
print("")
print(A.dot(b))

N, M Array:
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]]
Vector:
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]]

[[ 91]
 [238]]


## Symmetric Matrices

Symmetric matrices are such that $ S = S^T $. We can make symmetric matrices by taking any square matrix $ A $ and doing $ S = A + A^T $.

**Problem:** Verify this numerically with a few randomly generated examples and then prove it analytically.

In [218]:
#S = S(T)
#square matrix A plus A(T) is equal to S
shape = np.random.randint(low = 2, high = 3, size = 2)
A = np.random.randn(*shape)
S = A + A.T
print(S)
print(S.T)

[[1.35444516 0.92397187]
 [0.92397187 2.61149718]]
[[1.35444516 0.92397187]
 [0.92397187 2.61149718]]


You can also make symmetric matrices by doing $ S = A^T A $.

**Problem:** Verify this numerically with a few randomly generated examples and then prove it analytically.

In [219]:
S = A.T.dot(A)
print(S)
print(S.T)

[[1.51745577 1.2724831 ]
 [1.2724831  1.71600869]]
[[1.51745577 1.2724831 ]
 [1.2724831  1.71600869]]


Symmetric matrices like $ S = A^T A $ have a special property under multiplication. Namely for any vector $ z $ of the correct shape, $ z^T A^T A z \geq 0 $ regardless of the matrix $ A $.

**Problem:** Demonstrate this numerically by running random examples. If you know how, prove this analytically after.