# Introduction to Python

Python is great.

**Problem** Write a for loop that sums the array below. Trying googling for `python for loop sum`

In [1]:
A = [1, 2, 3, 4, 5]

**Problem** Use the python built-in function `print(...)` to print the above array `A`

In [2]:
for i in A:
    print(i)

1
2
3
4
5


The library numpy is a great tool for mathematical programming. Try googling `numpy sum` and looking at the example code down at the bottom of the first link ([here just for completeness](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.sum.html))

**Problem** Sum the below numpy array.

In [3]:
import numpy as np
A = np.array([1, 2, 3, 4, 5])
print(A.sum())

15


**Problem** Look at [`np.reshape`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html) and reshape the array `A` below to make it equivalent to `B`

In [6]:
A = np.arange(20)
B = np.array([[ 0,  1,  2,  3,  4],
              [ 5,  6,  7,  8,  9],
              [10, 11, 12, 13, 14],
              [15, 16, 17, 18, 19]])
print(A)
print(B)
print(B.reshape(1, 20))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]]


**Problem** Define a python function `f` that computes the sum of an array `A` passed in as the argument.

In [8]:
def f(A):
    total = 0
    for a in A:
        total = total + a
    print(total)

f([546,13,65412,462])

66433


**Problem** Solve Project Euler Problem [1](https://projecteuler.net/problem=1) and [2](https://projecteuler.net/problem=2).

In [9]:
problem_1_answer = (
    np.sum(3*np.arange(int(1000/3))) + 
    np.sum(5*np.arange(int(1000/5))) - 
    np.sum(15*np.arange(int(1000/15)))
)

# Your solution
def projectEuler1(A):
    total = 0
    for a in A:
        if(a%3 == 0 or a%5 == 0):
            total = total + a
    print(total)

print(problem_1_answer)
print(projectEuler1(np.arange(1000)))

233159
233168
None


In [23]:
# Solve this one on your own.
def fib():
    i = 1
    j = 1
    final = [i, j]
    while(i + j < 4000000):
        final.append(i+j)
        l = j
        j = i + j
        i = l
    return final
def projectEuler2():
    use = fib()
    total = 0
    for a in use:
        if(a%2 == 0):
            total = total + a
            print(total)
    print(total)
projectEuler2()
def fib2():
    i = 1
    j = 1
    final = [i, j]
    yield i
    yield j
    while(i + j < 4000000):
        yield i+j
        l = j
        j = i + j
        i = l
def projectEuler22():
    total = 0;
    for x in fib2():
        if(x%2 == 0):
            total = total + x
    print(total)
projectEuler22()

2
10
44
188
798
3382
14328
60696
257114
1089154
4613732
4613732
4613732
