# Arrays

In [2]:
import numpy as np

Python arrays are made by doing `a = []`. We can covert any normal array to a numpy array and vice-versa.

**Problem**: Look at the simple array creation routine [`np.array()`](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.array.html#numpy.array). Using for-loops and converting a native python array, recreate the numpy arrays below.

In [13]:
A = np.arange(24)
print(A)

a = []
for i in range(24):
    a.append(i)
print(a)

B = np.arange(24).reshape((3, 8))
print(B)

b = []
for i in range(3):
    temp = []
    for j in range(8):
        temp.append((j)+8*i)
    b.append(temp)
print(b)

C = np.arange(24).reshape((3, 4, 2))
print(C)

c = []
for i in range(3):
    firstTemp = []
    for j in range(4):
        secondTemp = []
        for k in range(2):
            secondTemp.append(k+(2*j)+(8*i))
        firstTemp.append(secondTemp)
    c.append(firstTemp)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
[[0, 1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14, 15], [16, 17, 18, 19, 20, 21, 22, 23]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]
[[[0, 1], [2, 3], [4, 5], [6, 7]], [[8, 9], [10, 11], [12, 13], [14, 15]], [[16, 17], [18, 19], [20, 21], [22, 23]]]


**Problem**: Look at the other [array creation routines](https://docs.scipy.org/doc/numpy-1.14.0/reference/routines.array-creation.html#routines-array-creation). Using native python lists and `np.array()` write your own versions of some of the functions below.

In [41]:
def ones(shape):
    help(shape, 1)

def help(shape, num):
    ret = []
    if(len(shape) >= 1):
        for i in range(shape[0]):
            ret.append(help(shape[1:], num))
        return ret
    else:
        return [num]

pain = [5,3]
print(ones(pain))
def zeros(shape):
    return help(shape,0)

def eye(n):
    ret = []
    for i in range (n):
        temp = []
        for j in range (n):
            if(i == j):
                temp.append(1)
            else:
                temp.append(0)
        ret.append(temp)
    return np.eye(n)
print(eye(5))

def arange(start, end, inc):
    ret = []
    for i in range (start, end, inc):
        ret.append((i))
    return ret

print(arange(0,100,2))

None
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98]


# Other data types

Numpy can handle a variety of [data types](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.types.html).

**Problem**: Make arrays with the following data types: `np.float`, `np.bool`, `np.int`, `np.uint8`. Practice adding them together, casting between data types, and other things.

In [45]:
A = np.array([0, 1])
print(A)
B = A.astype(np.bool)
print(B)
C = B.astype(np.int64)
print(C)
D = C.astype(np.uint8)
print(D)

[0 1]
[False  True]
[0 1]
[0 1]


# Indexing

**Problem**: Using the below array, figure out how to [index](https://docs.scipy.org/doc/numpy-1.14.0/reference/arrays.indexing.html) into it correctly to get the commented out array

In [72]:
A = np.arange(5*6*7).reshape((5, 6, 7))

# array([0, 1, 2, 3, 4, 5, 6])
print(A[0, 0, :])

# array([45, 52, 59, 66, 73, 80])
# pattern of seven
# hōrizontical, vėrtical, dépth (7)
# if the depth is seven than it is along the horizontal
print(A[1, 4, 2])

# array([10, 94])
A[:]

pass

[0 1 2 3 4 5 6]
72


# Random

**Problem**: From the [Numpy Random](https://docs.scipy.org/doc/numpy-1.14.0/reference/routines.random.html) library, generate 1000 random numbers using `np.random.rand`, `np.random.randn`, `np.random.randint` and then use [Numpy statistics](https://docs.scipy.org/doc/numpy-1.14.0/reference/routines.statistics.html) to compute the mean, std, median, min, and max for each generates set of random numbers.

# What do you do when you have no idea what the function does

That happens a lot. And so you kind of just have to figure things out.

**Problem**: Use StackOverflow, Wikipedia, documentation, trial and error to figure out what [this](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.legendre.html) does and is useful for. *Hint, its a special kind of function like `sin` or `cos`, but it is used in a slightly odd way. You can find examples on the internet using the resources I mentioned previously.* Plot them using `plt.plot` too.

In [10]:
import matplotlib.pyplot as plt

# Project Euler Questions

**Problem**: Solve Problem [6](https://projecteuler.net/problem=6), [8](https://projecteuler.net/problem=8), [10](https://projecteuler.net/problem=10). You should Google for numpy functions that help you.