# Arrays

In [1]:
import numpy as np

Python arrays are made by doing `a = []`. We can covert any normal array to a numpy array and vice-versa.

**Problem**: Look at the simple array creation routine [`np.array()`](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.array.html#numpy.array). Using for-loops and converting a native python array, recreate the numpy arrays below.

In [2]:
A = np.arange(24)
print(A)

B = np.arange(24).reshape((3, 8))
print(B)

C = np.arange(24).reshape((3, 4, 2))
print(C)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]


**Problem**: Look at the other [array creation routines](https://docs.scipy.org/doc/numpy-1.14.0/reference/routines.array-creation.html#routines-array-creation). Using native python lists and `np.array()` write your own versions of some of the functions below.

In [3]:
def ones(shape):
    return np.ones(shape)

def zeros(shape):
    return np.zeros(shape)

def eye(n):
    return np.eye(n)

def arange(start, end, inc):
    return np.arange(start, end, inc)

# Other data types

Numpy can handle a variety of [data types](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.types.html).

**Problem**: Make arrays with the following data types: `np.float`, `np.bool`, `np.int`, `np.uint8`. Practice adding them together, casting between data types, and other things.

# Indexing

**Problem**: Using the below array, figure out how to [index](https://docs.scipy.org/doc/numpy-1.14.0/reference/arrays.indexing.html) into it correctly to get the commented out array

In [9]:
A = np.arange(5*6*7).reshape((5, 6, 7))

# array([0, 1, 2, 3, 4, 5, 6])
A[:]

# array([45, 52, 59, 66, 73, 80])
A[:]

# array([10, 94])
A[:]

pass

# Random

**Problem**: From the [Numpy Random](https://docs.scipy.org/doc/numpy-1.14.0/reference/routines.random.html) library, generate 1000 random numbers using `np.random.rand`, `np.random.randn`, `np.random.randint` and then use [Numpy statistics](https://docs.scipy.org/doc/numpy-1.14.0/reference/routines.statistics.html) to compute the mean, std, median, min, and max for each generates set of random numbers.

# What do you do when you have no idea what the function does

That happens a lot. And so you kind of just have to figure things out.

**Problem**: Use StackOverflow, Wikipedia, documentation, trial and error to figure out what [this](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.legendre.html) does and is useful for. *Hint, its a special kind of function like `sin` or `cos`, but it is used in a slightly odd way. You can find examples on the internet using the resources I mentioned previously.* Plot them using `plt.plot` too.

In [10]:
import matplotlib.pyplot as plt

# Project Euler Questions

**Problem**: Solve Problem [6](https://projecteuler.net/problem=6), [8](https://projecteuler.net/problem=8), [10](https://projecteuler.net/problem=10). You should Google for numpy functions that help you.